name: GraphQLCI
on:
  push:
    branches:     
      - master
      - development
      - UAT
    paths: 
      - folder-1/**
      - folder-2/**
      - .github/workflows/ci-workflow.yml
env:
  REGION: us-east-2
  PROJECT_NAME: 'test1-graphql-codebuild'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # PRINT branch name
      - run: echo branch ${{ github.ref }}
      
      # SET DEPLOYMENT_ENV environment variable
      - run: echo "::set-env name=DEPLOYMENT_ENV::dev"
        if: ${{ github.ref == 'refs/heads/development' }}
      - run: echo "::set-env name=DEPLOYMENT_ENV::uat"
        if: ${{ github.ref == 'refs/heads/UAT' }}
      - run: echo "::set-env name=DEPLOYMENT_ENV::dev"
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1.0.3       
        with:
          project-name: ${{ env.DEPLOYMENT_ENV }}-${{ env.PROJECT_NAME }}
