name: CodeBuildPOC
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:     
      - master
      - development
      - UAT
env:
  REGION: us-east-2
  PROJECT_NAME: 'graphql'
  DEPLOYMENT_ENV: 'none'
jobs:
  # JOB to run change detection
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::set-env name=DEPLOYMENT_ENV::dev"
        if: ${{ github.ref == 'refs/heads/development' }}
      - run: echo "::set-env name=DEPLOYMENT_ENV::uat"
        if: ${{ github.ref == 'refs/heads/UAT' }}
      - run: echo "::set-env name=DEPLOYMENT_ENV::prod"
        if: ${{ github.ref == 'refs/heads/master' }}
  build:
    needs: pre-build
    if: ${{ $DEPLOYMENT_ENV == 'dev' || $DEPLOYMENT_ENV == 'uat' || $DEPLOYMENT_ENV == 'prod' }}
    name: CodeBuildJob
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.run_number }}
      - run: echo ${{ github.ref }}
      - run: echo ${{ env.DEPLOYMENT_ENV }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

