name: CodeBuildPOC
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:     
      - master
      - development
      - UAT
env:
  REGION: us-east-2
  PROJECT_NAME: 'graphql'
jobs:
  # JOB to run change detection
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - run: export DEPLOYMENT_ENV=dev
        if: ${{ github.ref == 'refs/heads/development' }}
      - run: export DEPLOYMENT_ENV=uat
        if: ${{ github.ref == 'refs/heads/UAT' }}
      - run: export DEPLOYMENT_ENV=prod
        if: ${{ github.ref == 'refs/heads/master' }}
      - run: echo ${{ env.DEPLOYMENT_ENV }}
  build:
    needs: pre-build
    name: CodeBuildJob
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.run_number }}
      - run: echo ${{ github.ref }}
      - run: echo ${{ env.DEPLOYMENT_ENV }}
      - run: echo ${{ env.PROJECT_NAME }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

