name: CodeBuildPOC
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:     
      - master
      - development
      - UAT
env:
  REGION: us-east-2
jobs:
  build:
    # Job name is CodeBuildPOC
    name: CodeBuildPOCJob
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.GITHUB_HEAD_REF }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
