name: CodeBuildPOC
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:     
      - master
      - development
      - UAT
env:
  REGION: us-east-2
jobs:
  build:
    # Job name is CodeBuildPOC
    name: CodeBuildPOCJob1
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.run_number }}
      - run: echo ${{ github.ref }}
      - run: echo ${{ env.REGION }}
      - run: echo $GITHUB_RUN_NUMBER
      - run: echo ${{ env.GITHUB_RUN_NUMBER }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: ${{ github.ref == 'refs/heads/master1' }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
  build-1:
    # Job name is CodeBuildPOC
    name: CodeBuildPOCJob2
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.run_number }}
      - run: echo ${{ github.ref }}
      - run: echo ${{ env.REGION }}
      - run: echo $GITHUB_RUN_NUMBER
      - run: echo ${{ env.GITHUB_RUN_NUMBER }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: ${{ github.ref == 'refs/heads/master1' }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
